### ISSUE TITLE
Scale bar question

### ISSUE THREAD

**Issue by briancohn** [davidcsterratt/retistruct#15]
https://github.com/davidcsterratt/retistruct/blob/master/pkg/retistructdemos/inst/extdata/Figure_6-data/right-contra/scale.csv

What is this number?
In this example, it says scale = 5.95. Does that mean that 1 ImageJ pixel is equal to 5.95mm? Or does it mean that 5.95 imageJ pixels are equal to one mm?
Thanks @davidcsterratt !

**Comment by davidcsterratt** [comment]
From the user guide, p 3: 

> *Specifying the scale* Optionally, the scale of the image can be specified by providing a file `scale.csv` in the same directory as the image and ROI files. This file should contain two lines, the first with the heading `Scale` and the second with the length of the side of a pixel in micrometres.

Actually, it doesn't have to be micrometres.

**Comment by briancohn** [comment]
thanks!
