### ISSUE TITLE
understanding how T.csv is composed

### ISSUE THREAD

**Issue by briancohn** [davidcsterratt/retistruct#16]
Hi @davidcsterratt 

<img width="1002" alt="pasted_image_7_12_17__1_49_am" src="https://user-images.githubusercontent.com/4623063/28109608-7abed002-66a4-11e7-9097-178e50c73086.png">

Is this the way that T.CSV is generated?

generating a final result of:
![image](https://user-images.githubusercontent.com/4623063/28109628-8b5982e0-66a4-11e7-98a9-010176c753ce.png)

**Comment by briancohn** [comment]
in particular the last tear goes over the last index; is that right?

**Comment by davidcsterratt** [comment]
The meaning of V0, VB, and VF is:
* V0 - point index of apex of tear
* VB - point index of vertex of tear in backward direction (gb pointers show this direction)
* VF - point index of vertex of tear in forward direction (gf pointers show this direction)
The function `labelTearPoints()` labels a set of three unlabelled points appropriately.

**Comment by briancohn** [comment]
thanks! 

# Functions
```
permute_tear_vertices <- function(list_of_tear_triplets){
	lapply(list_of_tear_triplets, function(x){
			retistruct::labelTearPoints(annotated_outline_with_tears,x)
			})
}

compose_tear_triplets_dataframe <- function(list_of_tear_triplets) {
         do.call('rbind',permute_tear_vertices(list_of_tear_triplets))
}

```
# Usage Example
```r
list_of_tear_triplets <- list(

			c(23,18,28),
			c(35,31,37),
			c(48,45,51),
			c(64,58,69),
			c(87,78,93),
			c(100,96,105),
			c(109,115,122),
			c(135,131,1)
			)
compose_tear_triplets_dataframe(list_of_tear_triplets)



```

**Comment by briancohn** [comment]
retistructgui is not reliable (not your fault I know) so I'm implementing a pipeline for retina markup that does not require it. It will be manual but it's not so bad.

People will just assemble files by writing down the vertex numbers:
<img width="957" alt="pasted_image_7_11_17__2_00_pm" src="https://user-images.githubusercontent.com/4623063/28090489-4e969306-6641-11e7-80c5-8345e2e4a485.png">

**Comment by briancohn** [comment]
we are investigating a possible approach with D3/javascript in the future as well

**Comment by davidcsterratt** [comment]
Interesting. The interface is definitely a weak point. I'd been thinking that some sort of integration with ImageJ/Fiji might be a way forward, but I'm not expert in that package, so I don't know how easy it would be to create an equivalent interface for marking up tears. Also, I think R is going to be better for producing plots, so I don't see the whole system moving to ImageJ.
