### ISSUE TITLE
functions to export

### ISSUE THREAD

**Issue by briancohn** [davidcsterratt/retistruct#17]
Hi David!

```The :: operator only works for functions that are in the namespace of that other package. Other functions, that weren’t exported, can be used with the ::: operator. But CRAN doesn’t allow the ::: operator. If you want to use functions that aren’t in that other package’s namespace, you need to either get the author to add it, or (if allowable by the package’s license) just incorporate the code directly into your own package.```

**Comment by briancohn** [comment]
let me know what your thoughts on this are.
Another alternative is that you could sign off on me including copies of your functions in my source code, with clear notes of your authorship of those functions. @davidcsterratt

**Comment by briancohn** [comment]
CRAN is giving me a persistent NOTE because I they're unexported

**Comment by davidcsterratt** [comment]
Sorry for the delay - the new version or retistruct is now submitted to CRAN.

**Comment by briancohn** [comment]
Thanks!!
