### ISSUE TITLE
Post-process mapping function for cartesian (x,y) to (phi,lambda)

### ISSUE THREAD

**Issue by bc** [davidcsterratt/retistruct#20]
I map datapoint locations by reconstructing the retina, and passing datapoints.csv through, so I will receive the phi/lambda coordinate for each of the input datapoints.

# Is there a way to output the X,Y --> phi,lambda function after retistruction is complete?

Desired use case:
```r
retistruct_object <- use_retistruct_to_reconstruct_retina(path_to_folder_with_markup_outline_etc)
point_on_sphere <- map_cartesian_to_spherical(model = retistruct_object, point_of_interest = c(x=100,y=10))
#point on sphere = c(phi,lambda)
```

**Comment by bc** [comment]
thanks!

**Comment by bc** [comment]
just following up on this. thanks again

**Comment by jlause** [comment]
Hey David,
I'd also be very interested in such a feature. Is there any chance it is coming with 0.6.1?
Cheers!
Jan.

**Comment by bc** [comment]
this is really helpful, thanks again for incorporating it!
