### ISSUE TITLE
Allow passing of verbose parameter

### ISSUE THREAD

**Issue by bc** [davidcsterratt/retistruct#22]
https://github.com/davidcsterratt/retistruct/blob/63ddb4719ca3f9759f7ea26c490795a04944563c/pkg/retistruct/R/spheristruct.R#L740

https://github.com/davidcsterratt/retistruct/blob/master/pkg/retistruct/R/spheristruct.R#L852

thanks!

**Comment by davidcsterratt** [comment]
I'm not clear what the issue is here - could you give a bit more explanation please?

**Comment by bc** [comment]
sure - there's no way to stop this from printing
![image](https://user-images.githubusercontent.com/13772726/41017800-6a6f217e-690b-11e8-91cd-fc90ae871e7a.png)

So i end up with hundreds of these:

![image](https://user-images.githubusercontent.com/13772726/41017822-975a1202-690b-11e8-868c-8eaa2f3284c2.png)

because there's no parameter that I can pass through that will kill the print message. This is the case for 2 functions:
![image](https://user-images.githubusercontent.com/13772726/41017861-d58b1bd4-690b-11e8-9c29-37fab565db1a.png)

![image](https://user-images.githubusercontent.com/13772726/41017876-ec296986-690b-11e8-8e63-9a612d906a87.png)

Ideally everything would be non-verbose by default, unless the users want to critically evaluate the stitching/FIRE, etc.

**Comment by bc** [comment]
thank you!!
