### ISSUE TITLE
Appropriate phi0 usage

### ISSUE THREAD

**Issue by bc** [davidcsterratt/retistruct#24]
Hi!

https://github.com/davidcsterratt/retistruct/blob/e39b13150e5be4880cb8cb816fb465a13ed442ae/pkg/retistruct/R/spheristruct.R#L372

What's the correct phi0 value if the retina composes exactly half of the sphere? What's a conservative default I can set for my users?

**Comment by davidcsterratt** [comment]
Exactly half the sphere would correspond to 0 degrees (i.e. 0 degrees latitude, the equator). The Retistruct paper has some data on what predicted values of phi0 should be for developing mouse eye. For other species, I don't know. One possibility for a future release is to predict phi0 by comparing the rim length and the area of the flattened retina, but I haven't completely thought this through.
