### ISSUE TITLE
internal interface for outline.roi and datapoints.csv

### ISSUE THREAD

**Issue by bc** [davidcsterratt/retistruct#26]
Hi David! I'm curious about alternative input approaches to Retistruct. For example, if the user has outline coordinates, and datapoint locations in the same coordinate frame, they would not need to use ImageJ for their outline input. Furthermore, I think you have an outline-simplification function that makes sure the input outline is not ridiculously complex, given the precision of the system.

Essentially, I'm trying to move away from the folder-based approach of Retistruct, so it takes in variables in the local environment. This would help me set up a less file-driven approach. What do you think?

**Comment by bc** [comment]
ideally, the input could be:
```
retistruct(other parameters, "path/to/datapoints.csv","path/to/outline.csv", T_dataframe, M_dataframe, ...)```

**Comment by davidcsterratt** [comment]
In principle, you should already be able to create StitchedOutlines ready for reconstruction by using a sequence of lower level functions, as seen in the format_csv.R file and the retistruct.read.markup() function. I think all the relevant ones are exported.

I'm thinking this might be the best approach, as there might be many possible permutations of arguments to custom functions.

**Comment by davidcsterratt** [comment]
I'm closing this for now - but feel free to reopen if the suggestion above doesn't work.
