### ISSUE TITLE
Improve user guide - in particular marking nasal and dorsal points

### ISSUE THREAD

**Issue by ZeitgeberH** [davidcsterratt/retistruct#39]
Hi David,
Nice work!
Could you please explain a little bit of  how to mark nasal pole or dorsal.  I found it hard to understand from the user manual.  And i keep getting "warning: no point within 0.25 inches", which disables the "reconstruct retina" button.
Best,
Ming

**Comment by davidcsterratt** [comment]
Thanks for the complement. Yes, the user manual could do with some updating. I have been working on it, I've uploaded the current version. There is still more to do, but it is more accurate.
