### ISSUE TITLE
could not find function "TriangulatedOutline"

### ISSUE THREAD

**Issue by kid030** [davidcsterratt/retistruct#50]
Hello, 

I am using a windows system and installed the package "retistruct" (v0.6.3). I tried the  demo("retistruct.method"), but ar error showed **"could not find function "TriangulatedOutline" "**.  I also tried demo(figure6) but it said: "no demo found for topic'figure6'". Did I miss any steps? 

Thanks!!

**Comment by davidcsterratt** [comment]
I'm guessing that you can't easily install v.0.7.2, which is still not released to CRAN. Please email me <david.c.sterratt@ed.ac.uk> and I can send you an installable package to test.

**Comment by kid030** [comment]
I managed to install v0.7.2 via GitHub, it was solved and worked very well. However, I met another problem (issue #51 ). 

Thanks.
