### ISSUE TITLE
retistructgui not available on CRAN for 3.3.1

### ISSUE THREAD

**Issue by bcohn12** [davidcsterratt/retistruct#9]
Hey could you take a look at this issue thread? I'm having trouble figuring out how to help a user install retistructgui
thanks!
Brian

https://github.com/lschmitz/retina/issues/1#issuecomment-235172793

**Comment by davidcsterratt** [comment]
Hello Brian,

sorry for the delay replying. It looks like the issue has sorted itself out now - but please let me know if not.

David.
